language: cpp

sudo: false

compiler:
  - clang

env:
  global:
   - secure: "MId6lh2WXvYg1bhirx2x4vcRZeZHPXjxFwzoxgk/Y6FQl9AbB4jZ83VVcOZzx3Un3UscKzpLZV5bB2j/NBBjlw1YxXwsFKFIGgiPQL/V1/ifHNwhFfzIVrMjtenrZUgy8twh020UQ+wISVPPcodp0Ty9T8ri99I/BXAGHFqDw2fyzvKaoWGw2PTSJ6nqlM2jGgqweeoDhKJL3BXuu26jnyQAN8W8DtNpvQae3ksDYEPiYsEVMaqI5ioc6sTWQ1sPWjU4GFVyiEQY4OPYd0Gw+6PgWPxlc+EYfFxJbTWUbKV+PfKXTnDz1a2SYNDXLthz/ElQdYB737gtDTLjBLPUGl2InrAqUzo1FmmCmvCmC9YRzLGct2EJzQXA5Ap9mUHIg2i09vj4yfg106UH7OO4j9cFQYNZufsfIg8BeuWoefXCxoRqYyF61OR0IRGxBIgkvjiSCglMokzPRspXadDtoVYPhgcGnHQUaG9L2cPizZ1fp5xjVQv0UyMdJLlT043n/X/vetRWQx6MQcpm9bUjKDuQwq6ShwWyt4d3d2AptHFy7KopO9nsO0hF8qkrtY6ga6PDVy3EnOqWHcdVN4W2DllKtTMgWGMk80Rae7ka3X2shRoEFj1TaG+16MkLmaiDq7x2zfbhHcVwMT5DvW8iYz6C6jcHwt2DVLxcDu8ufeE="

addons:
  apt:
    sources:
    - kalakris-cmake
    - boost-latest
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - cmake
    - libboost1.55-dev 
    - libboost-system1.55-dev
    - libboost-iostreams1.55-dev
    - libboost-python1.55-dev
    - libboost-thread1.55-dev
    - libboost-filesystem1.55-dev
    - clang-3.5
  coverity_scan:
    project:
      name: "hoangmle/metaSMT"
      description: "Build submitted via Travis CI"
    notification_email: hle@informatik.uni-bremen.de
    build_command_prepend: "./bootstrap.sh --deps deps --academic -m RELEASE build"
    build_command:   "make -C build -j"
    branch_pattern: coverity_scan

cache:
  apt: true
  directories:
  - deps

before_install:
  - git clone https://github.com/agra-uni-bremen/dependencies.git
  - export BOOST_ROOT=/usr CXX="clang++-3.5" CC="clang-3.5"

script: 
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make -C build -j; fi

after_success:
  - make -C build test

os:
  - linux
