language: cpp
dist: trusty

compiler:
    - gcc

env:
    matrix:
    # Boolector, STP and Yices2
    - SOLVERS="--academic -DmetaSMT_USE_CVC4=off"
    # CVC4
    - SOLVERS="-DCVC4_DIR=/usr/cvc4"

cache: apt
before_install:
    # Needed for gcc4.8
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    # Update package information
    - sudo apt-get update
    # Get gcc, Boost, gmp, gperf
    - sudo apt-get -y install gcc-4.8 g++-4.8 libboost-dev libgmp-dev gperf
    # Make gcc4.8 the default gcc version
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    # Get CVC4
    - wget http://www.informatik.uni-bremen.de/agra/systemc-verification/media/snapshots/cvc4-594301e.tar.gz
    - tar -xf cvc4-594301e.tar.gz
    - sudo mv cvc4 /usr

before_script:
    # Get dependencies
    - git clone https://github.com/agra-uni-bremen/dependencies.git
    # Bootstrap
    - export BOOST_ROOT=/usr
    - ./bootstrap.sh --deps deps ${SOLVERS} -m RELEASE build/
    - cd build

script: make

after_success:
    - make test
